//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.06 at 10:42:40 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mwiesner.com/MyOrder")
package com.mwiesner.myorder;
